name: Build & Push Docker Image | Compras QA

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Ingrese la versión de la imagen'
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_COMPRAS_QA }}
          password: ${{ secrets.DOCKER_PASS_COMPRAS }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: guidosantiagoreta/node-compras-qa:latest,guidosantiagoreta/node-compras-qa:${{ github.event.inputs.version }}
