name: Build & Push Docker Image | Cobranzas QA

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Ingrese la versión de la imagen'
        required: true  

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_COBRANZAS_QAS }}
          password: ${{ secrets.DOCKER_PASS_COBRANZAS_QAS }}
          
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            davidljm93/qa_cobranzas_dm:latest
            davidljm93/qa_cobranzas_dm:${{ github.event.inputs.version }}
