# Pipeline diseñado para automatizar el proceso de Docker en una instancia EC2 

name: SSH EC2 | Run Image QA Enviroment

on:
  workflow_run:
    workflows: ["Build & Push Docker Image | Compras QA"]
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_COMPRAS_TEST }}
          username: ${{ secrets.USER_COMPRAS }}
          key: ${{ secrets.SSH_COMPRAS_TEST }}
          script: |
                sudo yum update -y              # Actulizar 
                sudo yum install docker -y      # Instalar Docker
                sudo systemctl start docker     # Inicializar Docker
                sudo systemctl enable docker
                sudo docker rm -f compras_qa_container || true   # Remover el contenedor si exite
                sudo docker run -d --name compras_qa_container -p 3000:3000 --restart always guidosantiagoreta/node-compras-qa:latest
                sudo docker ps  # Chequear que el contenedor este corriendo
                sudo wget https://raw.githubusercontent.com/rijmjada/sprint-2/main/script.sh -O /home/ec2-user/script.sh   #node exporter herramienta de Prometheus
                sudo bash /home/ec2-user/script.sh
