name: SSH EC2 | Run Image QA Enviroment

on:
  workflow_run:
    workflows: ["Build & Push Docker Image | pagos QA"]
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_PAGOS_TEST }}
          username: ${{ secrets.USER_PAGOS }}
          key: ${{ secrets.SSH_PAGOS_TEST }}
          script: |
                sudo yum update -y              # Actulizar 
                sudo yum install docker -y      # Instalar Docker
                sudo systemctl start docker     # Inicializar Docker
                sudo systemctl enable docker
                sudo docker rm -f pagos_container || true   # Remover el contenedor si exite
                sudo docker run -d --name pagos_container -p 3000:3000 --restart always nikardo/pagosqa:latest
                sudo docker ps  # Chequear que el contenedor este corriendo
