name: SSH EC2 | Run Image QA Enviroment

on:
  workflow_run:
    workflows: ["Build & Push Docker Image | Ventas QA"]
    types:
      - completed

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_VENTAS_TEST }}
          username: ${{ secrets.QA_VENTAS_USER }}
          key: ${{ secrets.SSH_VENTAS_TEST }}
          script: |
                sudo yum update -y              # Actulizar 
                sudo yum install docker -y      # Instalar Docker
                sudo systemctl start docker     # Inicializar Docker
                sudo systemctl enable docker
                sudo docker rm -f ventas_container || true   # Remover el contenedor si exite
                sudo docker run -d --name ventas_container -p 3000:3000 --restart always diego1986/qa_ventas_diego_ormeno:latest
                sudo wget https://raw.githubusercontent.com/rijmjada/sprint-2/main/script.sh -O /home/ec2-user/script.sh
                sudo bash /home/ec2-user/script.sh
 
