name: OWASP ZAP PROVEEDORES 
on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: 'Ingrese la imagen [ ej: owner/repository_name:tag ]:'
        required: true

jobs:
  security_scan:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and run Docker image
        run: |
          sudo docker run -d -p 3000:3000 ${{ github.event.inputs.docker_image }}

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'http://localhost:3000'
          allow_issue_writing: true
          token: ${{ secrets.GH_TOKEN_PROVEEDORES }}

      - name: Upload ZAP Scan Report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.docker_image }}_zap_scan_report
          path: ${{ github.workspace }}/zap-report.html
